### ISSUE TITLE
allUserProfiles - user_ids query param not working as intended?

### ISSUE THREAD

**Issue by gccaldwell99** [ReelTalkers/reeltalk-backend#1]
The user_ids query param for allUserProfiles simply returns all users, instead of users with matching ids. Is this workings as intended?

**Comment by gregziegan** [comment]
So, this filtering is a total hack and much too slow. I'm going to close this and reopen a "fix filtering" issue.  The Graphene library has an active pull request for this django filtering integration and a new plugin system we need to look into.
